### PR TITLE
Add pure rust LZMA implementation

### PR DESCRIPTION
**Pull request by HoLLy-HaCKeR**
This PR adds a a pure rust LZMA backend to lift the requirement on the `cc` crate and its build requirements. It does so by adding the mandatory, mutually-exclusive features `lzma-sys` and `lzma-rs`. If a user of the library wishes to use the `replay-data` feature, they must choose either feature or the crate will not compile and give a clear error message indicating the what they must do.

This is a breaking change for users of the `replay-data` feature as they must enable a new feature to indicate which LZMA-backend they with to use.

### CODE REVIEW

**Comment by HoLLy-HaCKeR** [comment]
I pushed a change to the CI configuration so tests should run now, but I don't know if GitHub will run pipelines after I make changes to them.

**Comment by iptq** [comment]
Ok, that's fine. Thanks for the patch! I'll clean up some of the things regarding docs.rs features but this should be good to go.

**Comment by HoLLy-HaCKeR** [comment]
I wasn't able to find a way to enable one implementation by default (presumably I need rust-lang/cargo#1839), but it may be more ergonomic if you know a way to do it.

**Comment by iptq** [comment]
Yeeeep, I was just going down that rabbit hole haha. My inclination is just to use the pure-Rust implementation directly, but I'm not sure what the usage metrics on this are.

I think I'll just have `replay-data` and `replay-data-native-lzma`, where `replay-data` is enabled by default. I'll probably push an update to crates.io with these changes within the hour.

**Pull request merged**
