### PR TITLE
Adds osu!.db parser

### PR DESCRIPTION
**Pull request by nobbele**
Had to move the read_* functions to a more accessible location not locked behind the replay feature to make osudb not locked behind that either, also adds num, num-traits and num-derive as dependencies to make it easier to parse grade, mode, etc.

### CODE REVIEW

**Comment by iptq** [comment]
Nice! is this file.txt just some output from a test run?

**Comment by nobbele** [comment]
oh yeah forgot to remove that lol, will do it now

**Comment by iptq** [comment]
Works for me, i'll do a bit of cleaning up of the API code and push as 0.10

**Comment by nobbele** [comment]
about that, I don't know if it's intentional or not but replay doesn't compile at all, are you testing with `cargo test --all-features`?

**Comment by iptq** [comment]
Screwed it up by accident, should be working with all features now

**Pull request merged**
